;SERIAL COM
ORG 0H
MOV TMOD, #20H
MOV TH1, #-12D
MOV SCON, #50H
AGAIN: SETB TR1
    JB P1.0, LEDON
    MOV DPTR, #MES2
L2: CLR A
    MOVC A, @A+DPTR
    JZ EXIT
    ACALL SERIAL
    INC DPTR
    SJMP L2
LEDON: MOV DPTR, #MES1
L1: CLR A
    MOVC A, @A+DPTR
    JZ EXIT
    ACALL SERIAL
    INC DPTR
    SJMP L1
    CLR TR1
EXIT: SJMP AGAIN
SERIAL: MOV SBUF, A
    HERE: JNB TI, HERE
    CLR TI
    RET

ORG 300H
MES2: DB 'LED OFF', 0
MES1: DB 'LED ON', 0
END
