;"Interrupt has occured"
ORG 0000H
	SJMP 0030H

ORG 0030H
	MOV IE,#84H
	SETB TCON.2
	AGAIN: NOP
	NOP
	SJMP AGAIN 
	
ORG 0013H
	SJMP 0050H
	
	ORG 0050H 
		    MOV DPTR,#MY_COMM
	BACK:   CLR A
		    MOVC A,@A+DPTR
		    JZ DATA2
			ACALL COMM_SUB
			ACALL DELAY
			INC DPTR
			SJMP BACK
			
			DATA2: MOV DPTR,# MY_DATA
			BACK1: CLR A
		    MOVC A,@A+DPTR
			JZ EXIT
			ACALL DATA_SUB
			ACALL DELAY
			INC DPTR
			SJMP BACK1
			EXIT: RETI
			
			COMM_SUB: 
			CLR P3.7
			CLR P3.6
			SETB P3.5
			MOV P2,A
			CLR P3.5
			RET
			
			DATA_SUB: 
			SETB P3.7
			CLR P3.6
			SETB P3.5
			MOV P2,A
			CLR P3.5
			RET
			
			DELAY:
			MOV R0,#0FFH
			L2: MOV R1,#0FFH
			L1:DJNZ R1,L1
			DJNZ R0,L2
			RET 
			
			ORG 0300H
				MY_COMM: DB 38H,01H,0EH,06H,80H,0
					MY_DATA: DB "INT HAS OCCURED",0
			END